name: Build, Package, and Add Release Asset

on:
  release:
    types:
      - created  # Trigger the action when a new release is created

jobs:
  build_package_upload:
    runs-on: windows-latest  # You can also use 'windows-latest' for Windows runners

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'  # This is just an example, adjust to the latest .NET 5 version

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build C# library
      run: dotnet build --configuration Release --framework net48

    - name: Archive package
      run: .\package.ps1

    - name: Upload package as a release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/Sophon96.dvNoCableMU_${{ github.event.release.tag_name }}.zip
        asset_name: Sophon96.dvNoCableMU.zip
        asset_content_type: application/zip
